language: node_js 
os: linux
dist: xenial
node_js:
  - "10"
  - "12"
  - "14"
services: mongodb  
cache:  
  directories:
  - "node_modules"
install:
  - travis_wait npm install
script:
  - npm run lint
  - npm test
deploy:
  - provider: script
    cleanup: true
    script: chmod +x ./deploy.sh && ./deploy.sh
    on:
    branch: master